name: stripe_example
description: Demonstrates how to use the stripe plugin.

publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_stripe: ^1.2.0
  pay: ^1.0.1
  http: ^0.13.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
dependency_overrides:
  flutter_stripe:
    path: ../packages/stripe
  stripe_platform_interface:
    path: ../packages/stripe_platform_interface
  stripe_android:
    path: ../packages/stripe_android
  stripe_ios:
    path: ../packages/stripe_ios

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: OtomanopeeOne
      fonts:
        - asset: fonts/OtomanopeeOne.ttf