name: stripe
packages:
  - /**
scripts:
  analyze: melos exec -- flutter analyze
  format: melos exec -- flutter format .
  get: melos exec -- flutter pub get
  unittest: 
    run: melos exec -- flutter test
    select-package:
      dir-exists:
        - test
      scope: "*interface*"

  test: melos exec -- flutter test
  clean: melos exec -- flutter clean
  server: cd example/server/ && npm run start

